CREATE TABLE IF NOT EXISTS `flour_users` (
  `id` CHAR(36) NOT NULL DEFAULT '',
  `name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `created` DATETIME DEFAULT NULL,
  `modified` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `flour_login_tokens` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` CHAR(36) NOT NULL,
  `token` CHAR(32) NOT NULL,
  `duration` VARCHAR(32) NOT NULL,
  `used` TINYINT(1) NOT NULL DEFAULT '0',
  `created` DATETIME NOT NULL,
  `expires` DATETIME NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

